name: Release Setup

on:
  workflow_dispatch:
  release:
    types: [created]
permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build for Windows

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm pyinstaller

    - name: Build
      run: |
        cp ./main.py ./dist/main.py
        cd ./dist && pyinstaller main.py --onefile
        cp ./dist/main.exe timeline-windows.exe
        
    - name: Save output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: timeline-windows.exe
  build-linux:
    runs-on: ubuntu-latest
    name: Build for Linux

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm pyinstaller

    - name: Build
      run: |
        cp ./main.py ./dist/main.py
        cd ./dist && pyinstaller main.py --onefile
        cp ./dist/main timeline-linux
        
    - name: Save output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: timeline-linux
  build-macos:
    runs-on: macos-latest
    name: Build for macOS

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm pyinstaller

    - name: Build
      run: |
        cp ./main.py ./dist/main.py
        cd ./dist && pyinstaller main.py --onefile
        cp ./dist/main timeline-macos
        
    - name: Save output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: timeline-macos
  upload-build:
    runs-on: ubuntu-latest
    name: Upload Release Asset
    needs: [build-windows, build-macos, build-linux]

    steps:
      - uses: actions/checkout@v3
      - name: Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./dist
          
          echo Uploading Windows release...
          gh release upload ${{ github.event.release.tag_name }} timeline-windows.exe
          
          echo Uploading Linux release...
          gh release upload ${{ github.event.release.tag_name }} timeline-linux.exe

          echo Uploading macOS release...
          gh release upload ${{ github.event.release.tag_name }} timeline-macos.exe
